const lightCodeTheme = require('prism-react-renderer/themes/github');
const darkCodeTheme = require('prism-react-renderer/themes/dracula');

/** @type {import('@docusaurus/types').DocusaurusConfig} */
module.exports = {
  title: 'Intellective Documentation',
  tagline: 'Insert Tagline Here', //found under the hero 
  url: 'https://github.com/intellectivelab',
  baseUrl: '/',
  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',
  favicon: 'img/favicon.ico',
  organizationName: 'intellectivelab', // Usually your GitHub org/user name.
  projectName: 'docs.intellective.com', // Usually your repo name.
  themeConfig: {
    navbar: {
      title: '',
      logo: {
        alt: 'Unity Docs Logo',
        src: 'img/docs-logo-vector-small.svg',
        srcDark: 'img/docs-logo-vector-small-dark.svg',
      },
      items: [
        {
          position: 'left',
          label: 'Products',
          items: [
            {
              label: 'Unity 8',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Salesforce',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for nCino',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Dynamics',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for ICN',
              href: 'docs/unity-for-icn',
              docId: 'unity-overview',
            },
            {
              type: 'doc',
              href: 'docs/interchange/deployment',
              label: 'Interchange',
            }
          ],
        },
        {
          position: 'left',
          label: 'Unity Platform',
          items: [
            {
              label: 'Unity ExtJS',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity React',
              type: 'doc',
              docId: 'unity-overview',
            },
          ],
        },
        {
          position: 'left',
          label: 'Release Notes',
          items: [
            {
              type: 'autogenerated',
              dirName: 'release-notes',
            },
          ],
        },
        {
          position: 'left',
          label: 'Development',
          items: [
            {
              label: 'Unity 8',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Salesforce',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for nCino',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Dynamics',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for ICN',
              href: 'docs/unity-for-icn',
              docId: 'unity-overview',
            },
            {
              type: 'doc',
              href: 'docs/interchange/deployment',
              label: 'Interchange',
            }
          ],
        },
        {
          position: 'left',
          label: 'Learn',
          items: [
            {
              label: 'Unity 8',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Salesforce',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for nCino',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for Dynamics',
              type: 'doc',
              docId: 'unity-overview',
            },
            {
              label: 'Unity for ICN',
              href: 'docs/unity-for-icn',
              docId: 'unity-overview',
            },
            {
              type: 'doc',
              href: 'docs/interchange/deployment',
              label: 'Interchange',
            }
          ],
        },
        {
          position: 'left',
          label: 'More',
          items: [
            {
              href: 'https://www.intellective.com/blog/', 
              label: 'Blog', 
              position: 'left',
            },
          ],
        },
        {
          href: 'https://github.com/facebook/docusaurus',
          label: 'Contact Us',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Documentation',
              to: '/docs/intro',
            },
          ],
        },
        {
          title: 'Community',
          items: [
            {
              label: 'Stack Overflow',
              href: 'https://stackoverflow.com/questions/tagged/docusaurus',
            },
            {
              label: 'Discord',
              href: 'https://discordapp.com/invite/docusaurus',
            },
            {
              label: 'Twitter',
              href: 'https://twitter.com/docusaurus',
            },
          ],
        },
        {
          title: 'More',
          items: [
            {
              label: 'Blog',
              href: 'https://www.intellective.com/blog/',
            },
            {
              label: 'GitHub',
              href: 'https://github.com/intellectivelab',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} Intellective, Inc.`,
    },
    prism: {
      theme: lightCodeTheme,
      darkTheme: darkCodeTheme,
    },
  },
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        docs: {
          sidebarPath: require.resolve('./sidebars.js'),
          // Please change this to your repo.
          editUrl:
            'https://github.com/intellectivelabs/docs.intellectivelab.com/edit/master/',
        },
        blog: {
          showReadingTime: true,
          // Please change this to your repo.
          editUrl:
            'https://github.com/',
        },
        theme: {
          customCss: require.resolve('./src/css/custom.css'),
        },
      },
    ],
  ],
};
