/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // sidebarName: [{type: 'autogenerated', dirName: '.'}]
  
  whatIsUnitySidebar: [
    {
      type: 'autogenerated', 
      dirName: 'what-is-unity'
    }
  ],
  unitySidebar: [
    {
      type: 'autogenerated', 
      dirName: 'products/unity-8'
    }
  ],
  salesforceSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/unity-salesforce'
    }
  ],
  nCinoSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/unity-for-ncino'
    }
  ],
  dynamicsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/unity-for-dynamics'
    }
  ],
  icnSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/unity-for-icn'
    }
  ],
  interchangeSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/interchange'
    }
  ],
  enterpriseSidebar: [
    {
      type: 'autogenerated',
      dirName: 'products/enterprise-search'
    }
  ],
  developmentSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'development'
    }
  ],
  frameworksSidebar: [
    {
      type: 'autogenerated',
      dirName: 'frameworks'
    }
  ],
  releaseNotesSidebar: [
    {
      type: 'autogenerated', 
      dirName: 'release-notes',
    }
  ],
  learningSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    }
  ],
  

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
